on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: notomo/action-setup-nvim-lua@v1
      - run: luarocks install vusted

      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - name: Run tests
        env:
          VUSTED_NVIM: ${{ steps.vim.outputs.executable }}
        run: vusted .
